[colors.primary]
background = "#cccccc"
foreground = "#474747"
dim_foreground = "#8c8fa1"
bright_foreground = "#474747"

[colors.cursor]
text = "#474747"
cursor = "#eff1f5"

[colors.vi_mode_cursor]
text = "#eff1f5"
cursor = "#c5c4c4"

[colors.search.matches]
foreground = "#e6e6e6"
background = "#7d7d83"

[colors.search.focused_match]
foreground = "#eff1f5"
background = "#a2a2a2"

[colors.footer_bar]
foreground = "#eff1f5"
background = "#9f9f9f"

[colors.hints.start]
foreground = "#ffffff"
background = "#dfdfdf"

[colors.hints.end]
foreground = "#ffffff"
background = "#6c6f85"

[colors.selection]
text = "#eff1f5"
background = "#dfdfdf"

[colors.normal]
black = "#bcbcbc"
red = "#8b8b8b"
green = "#9f9f9f"
yellow = "#d9d9d9"
blue = "#a0a0a0"
magenta = "#b7b3b6"
cyan = "#7a7a7aff"
white = "#5c5f77"

[colors.bright]
black = "#acb0be"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#6c6f85"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
