[colors.primary]
background = "#B5BBB0"
foreground = "#585C62"
dim_foreground = "#6A6F71"
bright_foreground = "#454952"

[colors.cursor]
text = "#585C62"
cursor = "#585C62"

[colors.vi_mode_cursor]
text = "#585C62"
cursor = "#585C62"

[colors.search.matches]
foreground = "#e6e6e6"
background = "#7d7d83"

[colors.search.focused_match]
foreground = "#c3c3c3"
background = "#818181"

[colors.footer_bar]
foreground = "#d0d0d0"
background = "#9f9f9f"

[colors.hints.start]
foreground = "#b0b0b0"
background = "#cccccc"

[colors.hints.end]
foreground = "#b0b0b0"
background = "#cccccc"

[colors.selection]
text = "#e8e8e9"
background = "#bbbbbb"

[colors.normal]
black = "#3A414E"
red = "#694848"
green = "#5A6157"
yellow = "#AEA051"
blue = "#5D6178"
magenta = "#917788"
cyan = "#779193"
white = "#F5F6F4"

[colors.bright]
black = "#2e2b2b"
red = "#856464"
green = "#4b5f47"
yellow = "#98985b"
blue = "#52738a"
magenta = "#6f4564"
cyan = "#7b4747"
white = "#d5cccc"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
