[colors.primary]
background = "#cccccc"
foreground = "#474747"
dim_foreground = "#8c8fa1"
bright_foreground = "#474747"

[colors.cursor]
text = "#474747"
cursor = "#414141"

[colors.vi_mode_cursor]
text = "#acacac"
cursor = "#414141"

[colors.search.matches]
foreground = "#e6e6e6"
background = "#7d7d83"

[colors.search.focused_match]
foreground = "#c3c3c3"
background = "#818181"

[colors.footer_bar]
foreground = "#d0d0d0"
background = "#9f9f9f"

[colors.hints.start]
foreground = "#b0b0b0"
background = "#cccccc"

[colors.hints.end]
foreground = "#b0b0b0"
background = "#cccccc"

[colors.selection]
text = "#e8e8e9"
background = "#bbbbbb"

[colors.normal]
black = "#bcbcbc"
red = "#8b8b8b"
green = "#9f9f9f"
yellow = "#d9d9d9"
blue = "#a0a0a0"
magenta = "#b7b3b6"
cyan = "#7a7a7a"
white = "#5c5f77"

[colors.bright]
black = "#acb0be"
red = "#cac3c4"
green = "#8d9d89"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#7c7c7c"

[[colors.indexed_colors]]
index = 16
color = "#fe640b"

[[colors.indexed_colors]]
index = 17
color = "#dc8a78"
